### ISSUE TITLE
[QoL] Resource Pack cem folder

### ISSUE THREAD

**Issue by Gabo6480** [dorianpb/cem#31]
Make it so the mod looks for both "assets/dorianpb/cem" and "assets/minecraft/optifine/cem" by default, instead of requiring users to manually change the assets path

**Comment by Gabo6480** [comment]
This could also apply for "ender_dragon.jem" and "dragon.jem" but that's more debatable

**Comment by dorianpb** [comment]
I'm not going to do either

the reason why I purposely not load from the optifine folder by default is because actual optifine packs aren't always supported and I want to make it clear it's still somewhat experimental

the reason why it is dragon.jem and not ender_dragon.cem is because that's what minecraft calls the dragon

thanks for your feedback though!
