### ISSUE TITLE
[BUG] Renaming pig does not change texture. 

### ISSUE THREAD

**Issue by TheNerdyBlock** [dorianpb/cem#77]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

I have a texture pack that changes the texture of the pig when renaming it. It does not work with this mod, but does with Optifine. 
The texture pack is http://phoenixsc.me/download-links/technoblade-pig-1-19/

**Expected behavior**

**Screenshots**

Please post screenshots of what the model looks like in this mod and in Optifine
In Optifine it looks like this. 
![image](https://user-images.githubusercontent.com/48140896/177837854-bca72989-e511-4edd-a740-7964b6d43e7a.png)
In CEM it does not change the texture at all. 

**Desktop (please complete the following information):**

 - OS: Windows 11 
 - Java Version: OpenJDK version 17.0.3
 - Minecraft Version: 1.19

**Additional context**
I am using the Quilt mod loader and a few other Optifine compatibility mods like entity texture features.

**Comment by Phoveroth** [comment]
As far as I know this mod doesn't support random entity models so you can't make an entity's model change when it is named something and I don't think there are any other mods for fabric that do that so unfortunately we can't have this feature in fabric through resource packs but you can use this [mod](https://modrinth.com/mod/technomodel) that does exactly that or you can use this [resource pack](https://www.curseforge.com/minecraft/texture-packs/technoblade-pig) to make the pigs wear Technoblade's crown but this makes all the pigs wear it. Or maybe what you can do is use [Entity Texture Features](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric) mod that adds random entity textures. With this mod, you can make pigs that are named Technoblade wear crowns but the crown has to be in pigs' head rather than on top of their heads like in the screenshot because you can't change the entity's model with that mod just it's texture.

**Comment by TheNerdyBlock** [comment]
Ok, thank you, hopefully this feature will be added eventually.

**Comment by RaptaG** [comment]
> Ok, thank you, hopefully this feature will be added eventually.

This feature is not related to CEM but to ETF (Entity Texture Features). Make sure to use that mod as well.
